# Generated by Django 4.2.5 on 2023-09-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetStarted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=122)),
                ('Last_Name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('Contact', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=122)),
            ],
        ),
    ]
